alter table CUBAMAPEXAMPLE_SALES_PERSON add constraint FK_CUBAMAPEXAMPLE_SALES_PERSON_PHOTO foreign key (PHOTO_ID) references SYS_FILE(ID);
create index IDX_CUBAMAPEXAMPLE_SALES_PERSON_PHOTO on CUBAMAPEXAMPLE_SALES_PERSON (PHOTO_ID);
