-- begin CUBAMAPEXAMPLE_SALES_PERSON
alter table CUBAMAPEXAMPLE_SALES_PERSON add constraint FK_CUBAMAPEXAMPLE_SALES_PERSON_TERRITORY foreign key (TERRITORY_ID) references CUBAMAPEXAMPLE_SALES_TERRITORY(ID)^
alter table CUBAMAPEXAMPLE_SALES_PERSON add constraint FK_CUBAMAPEXAMPLE_SALES_PERSON_PHOTO foreign key (PHOTO_ID) references SYS_FILE(ID)^
create index IDX_CUBAMAPEXAMPLE_SALES_PERSON_PHOTO on CUBAMAPEXAMPLE_SALES_PERSON (PHOTO_ID)^
create index IDX_CUBAMAPEXAMPLE_SALES_PERSON_TERRITORY on CUBAMAPEXAMPLE_SALES_PERSON (TERRITORY_ID)^
-- end CUBAMAPEXAMPLE_SALES_PERSON
-- begin CUBAMAPEXAMPLE_SALES_ORDER
alter table CUBAMAPEXAMPLE_SALES_ORDER add constraint FK_CUBAMAPEXAMPLE_SALES_ORDER_SALES_PERSON foreign key (SALES_PERSON_ID) references CUBAMAPEXAMPLE_SALES_PERSON(ID)^
create index IDX_CUBAMAPEXAMPLE_SALES_ORDER_SALES_PERSON on CUBAMAPEXAMPLE_SALES_ORDER (SALES_PERSON_ID)^
-- end CUBAMAPEXAMPLE_SALES_ORDER
